# Generated by Django 3.2.10 on 2021-12-19 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='timesamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
