# Generated by Django 3.2.10 on 2021-12-19 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_review_timesamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='timesamp',
            new_name='timestamp',
        ),
    ]
