# Generated by Django 3.2.10 on 2021-12-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_faq_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='product.product'),
        ),
    ]
