# Generated by Django 3.2.10 on 2022-01-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20220104_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/media/defaults/noimg.png', upload_to='products/categories/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/media/defaults/noimg.png', upload_to='products/collections/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='type',
            name='thumbnail',
            field=models.ImageField(blank=True, default='/media/defaults/noimg.png', upload_to='products/types/%Y/%m/%d'),
        ),
    ]
