# Generated by Django 3.2.10 on 2022-01-08 04:37

from django.db import migrations, models
import django


def migrate_inventory_id(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    for product in Product.objects.all():
        product.inventory_id = product.id
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20220104_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_id',
            field=models.CharField(
                db_index=True, max_length=10, default=0,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_inventory_id),
        migrations.AlterField(
            model_name='product',
            name='inventory_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[
                                      django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_rating',
            field=models.PositiveBigIntegerField(default=0),

        ),
    ]
