# Generated by Django 3.2.10 on 2022-01-08 13:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20220108_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimentions',
            field=models.CharField(default='100*100', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, default='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='description'),
        ),
    ]
