# Generated by Django 3.2.10 on 2022-01-08 13:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20220108_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care',
            field=ckeditor.fields.RichTextField(blank=True, default='take care'),
        ),
    ]
