# Generated by Django 3.2.10 on 2022-01-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20220113_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='value',
            field=models.CharField(
                default='#8d0020', max_length=10, verbose_name='color value eg. #FFF'),
        ),
    ]
