# Generated by Django 3.2.10 on 2021-12-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name_plural': 'Coupons'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='percentage',
            field=models.BooleanField(default=False),
        ),
    ]
