# Generated by Django 3.2.10 on 2021-12-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_alter_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default/images/profile_pic.png', upload_to='profile_pics/%Y/%m/%d'),
        ),
    ]
