# Generated by Django 3.2.10 on 2021-12-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
        ),
    ]
