# Generated by Django 3.2.10 on 2021-12-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0009_connectemails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectemails',
            options={'verbose_name_plural': 'ConnectEmails'},
        ),
    ]
