# Generated by Django 3.2.10 on 2021-12-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0010_alter_connectemails_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectEmails',
        ),
    ]
