# Generated by Django 3.2.10 on 2021-12-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0011_delete_connectemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='India', max_length=200),
        ),
    ]
