# Generated by Django 3.2.10 on 2022-01-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0013_remove_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='abc@mail.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
