# Generated by Django 3.2.10 on 2022-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0014_otp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
