# Generated by Django 3.2.10 on 2022-01-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0015_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='created',
        ),
    ]
