# Generated by Django 3.2.10 on 2022-01-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0018_alter_otp_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='Uttar Pradesh', max_length=50),
            preserve_default=False,
        ),
    ]
