# Generated by Django 3.2.10 on 2022-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0019_useraddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='line1',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='line2',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
