# Generated by Django 3.2.10 on 2021-12-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_alter_order_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorPayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('rp_id', models.CharField(max_length=30, unique=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='razor_pay_order', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('payment_id', models.CharField(max_length=30)),
                ('payment_sig', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
                ('razorpay_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='razor_pay.razorpayorder')),
            ],
        ),
    ]
