# Generated by Django 3.2.10 on 2021-12-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('razor_pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayorder',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
