# Generated by Django 3.2.10 on 2022-01-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_static', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexSliders',
            new_name='IndexSlider',
        ),
        migrations.RenameModel(
            old_name='ShopSliders',
            new_name='ShopSlider',
        ),
    ]
