# Generated by Django 4.0 on 2021-12-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_static', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
