# Generated by Django 3.2.10 on 2022-01-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_ordertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_tracking', to='orders.order'),
        ),
    ]
