# Generated by Django 3.2.10 on 2022-01-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_ordertracking_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipRocketToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
