# Generated by Django 3.2.10 on 2022-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_ordertracking_shiprocket_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_invoice_id',
            field=models.CharField(default='nil', max_length=30),
        ),
    ]
