# Generated by Django 3.2.10 on 2022-01-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_razorpay_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='shiprocket_shipment_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
