# Generated by Django 3.2.10 on 2022-01-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_ordertracking_shiprocket_shipment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
